(()=>{
const orbit=document.querySelector('.orbit'),nodes=document.getElementById('orbit-nodes'),grid=document.getElementById('project-grid'),filters=document.getElementById('project-filters'),toggle=document.getElementById('orbit-toggle'),viewer=document.getElementById('project-viewer'),media=document.getElementById('project-media'),mq=matchMedia('(prefers-reduced-motion: reduce)');
let projects=[],current=null,page=0,returnFocus=null,angle=0,raf=0,last=0,inView=false,hover=false,focused=false,userPaused=mq.matches,category='All';const orbitButtons=[];
const titles={'Matte paintaing':'Matte Painting','GTA Glass&Scroll Animation':'GTA — Glass & Scroll Animation','Monogram Motion shital pati':'Shital Pati — Monogram Motion','Pop up':'Pop-up Commercial','L Shape':'L-Shape Commercial','POSTER 1':'Poster Study 01','POSTER 6':'Poster Study 06','POSTER 7':'Poster Study 07','Acid-poster ( pAUL Walker)':'Paul Walker — Poster','ACEM Social media post':'ACEM — Study Abroad','Nextjob Social Media Post':'NextJobz','Ordinary':'Beauty — Black Friday','ata':'Bashundhara Atta','bongflix':'Bongflix','drinko':'Drinko','nescafe':'Nescafé','savoy':'Savoy'};
const title=p=>titles[p.title]||p.title;
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n}
function select(cat,scroll=false){category=cat;filters.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===cat)));const shown=projects.filter(p=>cat==='All'||p.category===cat);document.getElementById('project-heading').textContent=cat==='All'?'All projects':cat;document.getElementById('project-count').textContent=shown.length+' projects';grid.replaceChildren();grid.scrollLeft=0;for(const p of shown){const article=el('article','project-card'),button=el('button'),cover=el('div','project-cover'),image=el('img');image.src=p.cover;image.alt=title(p)+' — '+p.category;image.loading='lazy';image.width=650;image.height=650;cover.append(image,el('span','project-kind',p.type==='video'?'▶ Play film':p.type==='document'?p.pages.length+' pages ↗':'View design ↗'));button.append(cover,el('h4','',title(p)),el('p','',p.category));button.setAttribute('aria-label','Open '+title(p));button.addEventListener('click',()=>openProject(p,button));article.append(button);grid.append(article)}requestAnimationFrame(updateCarousel);if(scroll)document.getElementById('project-heading').scrollIntoView({behavior:mq.matches?'instant':'smooth',block:'start'})}
function renderPage(){media.replaceChildren();if(current.type==='video'){const video=el('video');video.src=current.video;video.poster=current.cover;video.controls=true;video.playsInline=true;video.preload='metadata';video.setAttribute('aria-label',title(current));media.append(video)}else{const img=el('img');img.src=current.pages[page];img.alt=title(current)+(current.type==='document'?' — page '+(page+1):'');media.append(img)}const n=current.pages.length;document.getElementById('page-count').textContent=current.type==='video'?'Motion Graphics':current.type==='document'?'Page '+(page+1)+' / '+n:current.category;document.getElementById('page-prev').disabled=page<=0;document.getElementById('page-next').disabled=page>=n-1;document.getElementById('page-prev').hidden=current.type!=='document';document.getElementById('page-next').hidden=current.type!=='document'}
function openProject(p,button){current=p;page=0;returnFocus=button;document.getElementById('project-title').textContent=title(p);document.getElementById('project-category').textContent=p.category;renderPage();viewer.showModal();document.body.classList.add('viewer-open');sync()}
document.getElementById('project-close').addEventListener('click',()=>viewer.close());viewer.addEventListener('close',()=>{const v=media.querySelector('video');if(v){v.pause();v.removeAttribute('src');v.load()}media.replaceChildren();document.body.classList.remove('viewer-open');returnFocus?.focus();sync()});
function turn(d){if(current?.type!=='document')return;const next=page+d;if(next>=0&&next<current.pages.length){page=next;renderPage()}}
document.getElementById('page-prev').addEventListener('click',()=>turn(-1));document.getElementById('page-next').addEventListener('click',()=>turn(1));viewer.addEventListener('keydown',e=>{if(current?.type==='document'&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault();turn(e.key==='ArrowRight'?1:-1)}});viewer.addEventListener('click',e=>{if(e.target===viewer){const b=viewer.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)viewer.close()}});
function stopped(){return userPaused||mq.matches||hover||focused||!inView||document.hidden||viewer.open||document.body.classList.contains('motion-paused')}
function position(){const w=orbit.clientWidth,h=orbit.clientHeight;orbitButtons.forEach((b,i)=>{const a=angle+i*Math.PI*2/orbitButtons.length,rx=w*.39,ry=h*.36,x=w/2+Math.cos(a)*rx-b.offsetWidth/2,y=h/2+Math.sin(a)*ry-b.offsetHeight/2;b.style.transform=`translate(${x}px,${y}px)`;b.style.zIndex=String(Math.round((Math.sin(a)+1)*10)+1)})}
function tick(t){raf=0;if(stopped()){last=0;return}if(last)angle+=Math.min(t-last,50)*.000035;last=t;position();raf=requestAnimationFrame(tick)}
function sync(){cancelAnimationFrame(raf);last=0;const paused=userPaused||mq.matches||document.body.classList.contains('motion-paused');toggle.textContent=paused?'Play orbit ▷':'Pause orbit Ⅱ';toggle.setAttribute('aria-pressed',String(paused));if(!stopped())raf=requestAnimationFrame(tick)}
toggle.addEventListener('click',()=>{userPaused=!userPaused;sync()});orbit.addEventListener('pointerenter',()=>{hover=true;sync()});orbit.addEventListener('pointerleave',()=>{hover=false;sync()});orbit.addEventListener('focusin',()=>{focused=true;sync()});orbit.addEventListener('focusout',e=>{if(!orbit.contains(e.relatedTarget)){focused=false;sync()}});new ResizeObserver(position).observe(orbit);new IntersectionObserver(es=>{inView=es[0].isIntersecting;sync()},{threshold:.1}).observe(orbit);new MutationObserver(sync).observe(document.body,{attributes:true,attributeFilter:['class']});document.addEventListener('visibilitychange',sync);mq.addEventListener('change',sync);
const previous=document.getElementById('carousel-prev'),nextButton=document.getElementById('carousel-next'),counter=document.getElementById('carousel-position');
function updateCarousel(){const cards=[...grid.children],box=grid.getBoundingClientRect(),visible=cards.map((c,i)=>({i,b:c.getBoundingClientRect()})).filter(x=>x.b.right>box.left+8&&x.b.left<box.right-8);previous.disabled=grid.scrollLeft<=2;nextButton.disabled=grid.scrollLeft>=grid.scrollWidth-grid.clientWidth-2;counter.textContent=visible.length?(visible[0].i+1)+'–'+(visible.at(-1).i+1)+' of '+cards.length:'No projects';}
function moveCarousel(direction){const card=grid.firstElementChild;if(!card)return;const step=card.getBoundingClientRect().width+parseFloat(getComputedStyle(grid).gap||24);grid.scrollBy({left:direction*step,behavior:mq.matches?'instant':'smooth'})}
previous.addEventListener('click',()=>moveCarousel(-1));nextButton.addEventListener('click',()=>moveCarousel(1));let scrollFrame=0;grid.addEventListener('scroll',()=>{cancelAnimationFrame(scrollFrame);scrollFrame=requestAnimationFrame(updateCarousel)},{passive:true});new ResizeObserver(updateCarousel).observe(grid);grid.addEventListener('keydown',e=>{if(e.target!==grid)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();moveCarousel(e.key==='ArrowRight'?1:-1)}else if(e.key==='Home'||e.key==='End'){e.preventDefault();grid.scrollTo({left:e.key==='Home'?0:grid.scrollWidth,behavior:mq.matches?'instant':'smooth'})}});
fetch('projects.json').then(r=>{if(!r.ok)throw Error('load');return r.json()}).then(data=>{projects=data;const cats=[...new Set(data.map(p=>p.category))];document.getElementById('orbit-total').textContent=data.length+' projects · '+cats.length+' disciplines';for(const cat of ['All',...cats]){const b=el('button','',cat);b.dataset.category=cat;b.setAttribute('aria-pressed',String(cat==='All'));b.addEventListener('click',()=>select(cat));filters.append(b)}for(const cat of cats){const p=data.find(p=>p.category===cat),b=el('button','orbit-node'),img=el('img');img.src=p.cover;img.alt='';b.append(img,el('span','',cat));b.setAttribute('aria-label','Explore '+cat+' projects');b.addEventListener('click',()=>select(cat,true));nodes.append(b);orbitButtons.push(b)}select('All');position();sync()}).catch(()=>{document.getElementById('projects-error').hidden=false;document.getElementById('project-count').textContent='Unavailable'});
})();
