(()=>{
const stage=document.querySelector('.quote-stage'),cards=[...stage.querySelectorAll('.quote-card')],play=document.getElementById('quote-play'),progress=stage.querySelector('.quote-progress span'),count=document.getElementById('quote-count'),announcement=document.getElementById('quote-announcement'),mq=matchMedia('(prefers-reduced-motion: reduce)');
let index=0,busy=false,userPaused=mq.matches,inView=false,hover=false,focused=false,elapsed=0,last=0,raf=0;
function stopped(){return userPaused||mq.matches||document.body.classList.contains('motion-paused')||document.hidden||!inView||hover||focused}
function position(){cards.forEach((card,i)=>{const p=(i-index+cards.length)%cards.length;card.dataset.position=p;card.setAttribute('aria-hidden',String(p!==0));});count.textContent=String(index+1).padStart(2,'0')+' / 03'}
function next(direction=1,manual=false){if(busy)return;busy=true;elapsed=0;progress.style.transform='scaleX(0)';const old=cards[index];old.classList.add('leaving');setTimeout(()=>{old.classList.remove('leaving');index=(index+direction+cards.length)%cards.length;position();if(manual)announcement.textContent='Testimonial '+(index+1)+' of 3. '+cards[index].querySelector('blockquote').textContent;busy=false},mq.matches?0:450)}
function tick(t){raf=0;if(stopped()){last=0;return}if(last&&!busy)elapsed+=Math.min(t-last,100);last=t;progress.style.transform='scaleX('+Math.min(elapsed/6500,1)+')';if(elapsed>=6500)next();raf=requestAnimationFrame(tick)}
function sync(){cancelAnimationFrame(raf);last=0;const paused=userPaused||mq.matches||document.body.classList.contains('motion-paused');play.textContent=paused?'Play ▷':'Pause Ⅱ';play.setAttribute('aria-pressed',String(paused));play.setAttribute('aria-label',paused?'Play testimonial autoplay':'Pause testimonial autoplay');if(!stopped())raf=requestAnimationFrame(tick)}
function manual(d){userPaused=true;next(d,true);sync()}
document.getElementById('quote-prev').addEventListener('click',()=>manual(-1));document.getElementById('quote-next').addEventListener('click',()=>manual(1));play.addEventListener('click',()=>{userPaused=!userPaused;sync()});stage.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();manual(e.key==='ArrowRight'?1:-1)}});stage.addEventListener('mouseenter',()=>{hover=true;sync()});stage.addEventListener('mouseleave',()=>{hover=false;sync()});stage.addEventListener('focusin',()=>{focused=true;sync()});stage.addEventListener('focusout',e=>{if(!stage.contains(e.relatedTarget)){focused=false;sync()}});
let start=null;stage.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse')start={x:e.clientX,y:e.clientY}},{passive:true});stage.addEventListener('pointerup',e=>{if(start){const x=e.clientX-start.x,y=e.clientY-start.y;if(Math.abs(x)>50&&Math.abs(x)>Math.abs(y))manual(x<0?1:-1);start=null}},{passive:true});stage.addEventListener('pointercancel',()=>start=null,{passive:true});
new IntersectionObserver(es=>{inView=es[0].isIntersecting;sync()},{threshold:.35}).observe(stage);new MutationObserver(sync).observe(document.body,{attributes:true,attributeFilter:['class']});document.addEventListener('visibilitychange',sync);mq.addEventListener('change',sync);position();sync();
})();
